config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#show'
  resources :step_counts
  resources :weights
  resources :choloric_intakes
  resources :exercises
  resources :exercise_types
  resources :dashboards

end

app/controllers/exercise_types_controller.rb
class ExerciseTypesController < ApplicationController
  before_action :set_exercise_type, only: [:show, :edit, :update, :destroy]

  def index
    @exercise_types = ExerciseType.all
  end

  def new
    @exercise_type = ExerciseType.new
  end

  def edit
  end

  def show
  end

  def create
    @exercise_type = ExerciseType.new(exercise_type_params)

    respond_to do |format|
      if @exercise_type.save
        format.html { redirect_to @exercise_type, notice: 'Exercise type was successfully created.' }
        format.json { render :show, status: :created, location: @exercise_type }
      else
        format.html { render :new }
        format.json { render json: @exercise_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercise_types/1
  # PATCH/PUT /exercise_types/1.json
  def update
    respond_to do |format|
      if @exercise_type.update(exercise_type_params)
        format.html { redirect_to @exercise_type, notice: 'Exercise type was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise_type }
      else
        format.html { render :edit }
        format.json { render json: @exercise_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exercise_type.destroy
    respond_to do |format|
      format.html { redirect_to exercise_types_url, notice: 'Step count was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def exercise_type_params
      params.require(:exercise_type).permit(:name)
    end

    def set_exercise_type
      @exercise_type = ExerciseType.find(params[:id])
    end
end

app/helpers/exercise_types_helper.rb
module ExerciseTypesHelper
end

app/views/exercise_types/_form.html.erb
<%= form_for(@exercise_type) do |f| %>
  <% if @exercise_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise_type.errors.count, "error") %> prohibited this weight from being saved:</h2>

      <ul>
      <% @exercise_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercise_types/edit.html.erb
<h1>Editing Step Count</h1>

<%= render 'form' %>

<div class="actions">
<%= link_to 'Show', @exercise_type %> |
</div>

<div class="actions">
<%= link_to 'Back', exercise_types_path %>
</div>

app/views/exercise_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exercise Types</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercise_types.each do |exercise_type| %>
      <tr>
        <td><%= exercise_type.name %></td>
        <td><%= link_to 'Show', exercise_type %></td>
        <td><%= link_to 'Edit', edit_exercise_type_path(exercise_type) %></td>
        <td><%= link_to 'Destroy', exercise_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="actions">
<p><%= link_to 'New Exercise Type', new_exercise_type_path %></p>
</div>
<div class="actions">
<p><%= link_to "Homepage", root_path %>
</div>

app/views/exercise_types/new.html.erb
<h1>New Exercise Type</h1>

<%= render 'form' %>

<div class="actions">
<%= link_to 'Back', new_exercise_path %>
</div>

app/views/exercise_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Exercise Type:</strong>
  <%= @exercise_type.name %>
</p>

<div class="actions">
  <%= link_to 'Edit', edit_exercise_type_path(@exercise_type) %> |
  <%= link_to 'Back', exercise_types_path %>
</div>

<div class="actions">
  <%= link_to "Homepage", root_path %>
</div>