config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#show'
  resources :step_counts
  resources :weights
  resources :choloric_intakes
  resources :exercises
  resources :exercise_types
  resources :dashboards

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  def index
    @exercises = Exercise.all
  end

  def new
    @exercise = Exercise.new
  end

  def edit
  end

  def show
    @heart_rate = Exercise.heart_rate
  end

  def create
    @exercise = Exercise.new(exercise_params)
    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def exercise_params
      params.require(:exercise).permit(:calories_burned, :duration, :exercise_type_id, :name, :age, :exertion)
    end

    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this weight from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Jogging" %>
    <%= f.radio_button :name, "Jogging", :value => "Jogging" %>
    <%= f.label :name, "Swimming" %>
    <%= f.radio_button :name, "Swimming", :value => "Swimming" %>
    <%= f.label :name, "Cycling" %>
    <%= f.radio_button :name, "Cycling", :value => "Cycling" %>
    <%= f.label :name, "Muscle Training" %>
    <%= f.radio_button :name, "Muscle Training", :value => "Muscle Training " %>
  </div>

  <div class="field">
    <%= f.label :age, "Age" %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <p> Rate your level of exertion </p>
    <%= f.label :exertion, "Low" %>
    <%= f.radio_button :exertion, "Low" %>
    <%= f.label :exertion, "Medium"  %>
    <%= f.radio_button :exertion, "Medium" %>
    <%= f.label :exertion, "High" %>
    <%= f.radio_button :exertion, "High" %>
  </div>

  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercises</h1>

<%= render 'form' %>

<div class="actions">
<%= link_to 'Show', @exercise %> |
</div>

<div class="actions">
<%= link_to 'Back', exercises_path %>
</div>

app/views/exercises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exercises</h1>

<table>
  <thead>
    <tr>
      <th>Calories Burned</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= calories_lost(@heart_rate) %></td>
        <td><%= exercise.duration %></td>
        <td><%= link_to 'New', exercises_path %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="actions">
<p><%= link_to "Homepage", root_path %></p>
</div>
<div class="actions">
<p><%= link_to 'New Exercise', new_exercise_path %><p>
</div>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form' %>

<div class="actions">
<%= link_to 'Back', exercises_path %>
</div>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calories Burned:</strong>
  <%= @exercise.calories_burned %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @exercise.duration %> minutes
</p>

<p>
  <strong>Exercise:</strong>
  <%= @exercise.name %>
</p>

<div class="actions">
  <%= link_to 'Edit', edit_exercise_path(@exercise) %> |
  <%= link_to 'Back', exercises_path %>
</div>

<div class="actions">
  <%= link_to "Homepage", root_path %>
</div>