config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#show'
  resources :step_counts
  resources :weights
  resources :choloric_intakes
  resources :exercises
  resources :exercise_types
  resources :dashboards

end

app/models/choloric_intake.rb
class CholoricIntake < ActiveRecord::Base

  def self.total_calories(date)
    total_calories = ConsumedCalory.where(consumed_on: date).sum(:total)
    total_calories_burned = PerformedExercise.where(done_on: date).sum(:calories_burned)
    total_calories - total_calories_burned
  end
end

app/controllers/choloric_intakes_controller.rb
class CholoricIntakesController < ApplicationController
  before_action :set_choloric_intake, only: [:show, :edit, :update, :destroy]

  def index
    @choloric_intake = CholoricIntake.all
  end

  def new
    @choloric_intake = CholoricIntake.new
  end

  def edit
  end

  def show
    @total_calories = CholoricIntake.total_calories
  end

  def create
    @choloric_intake = CholoricIntake.new(choloric_intake_params)

    respond_to do |format|
      if @choloric_intake.save
        format.html { redirect_to @choloric_intake, notice: 'Choloric intake was successfully created.' }
        format.json { render :show, status: :created, location: @choloric_intake }
      else
        format.html { render :new }
        format.json { render json: @choloric_intake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choloric_intakes/1
  # DELETE /choloric_intakes/1.json
  def destroy
    @choloric_intake.destroy
    respond_to do |format|
      format.html { redirect_to choloric_intakes_url, notice: 'Step count was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @choloric_intake.update(choloric_intake_params)
        format.html { redirect_to @choloric_intake, notice: 'Calories were successfully updated.' }
        format.json { render :show, status: :ok, location: @choloric_intake }
      else
        format.html { render :edit }
        format.json { render json: @choloric_intake.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def choloric_intake_params
      params.require(:choloric_intake).permit(:calories, :date)
    end

    def set_choloric_intake
      @choloric_intake = CholoricIntake.find(params[:id])
    end
end

app/helpers/choloric_intakes_helper.rb
module CholoricIntakesHelper
  

end

app/views/choloric_intakes/_form.html.erb
<%= form_for(@choloric_intake) do |f| %>
  <% if @choloric_intake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@choloric_intake.errors.count, "error") %> prohibited this weight from being saved:</h2>

      <ul>
      <% @choloric_intake.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :calories %><br>
    <%= f.number_field :calories %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choloric_intakes/edit.html.erb
<h1>Editing Calories </h1>

<%= render 'form' %>

<div class="actions">
<%= link_to 'Show', @choloric_intake %> |
</div>

<div class="actions">
<%= link_to 'Back', choloric_intake_path %>
</div>

app/views/choloric_intakes/index.html.erb
<p id = "notice"><%= notice %></p>
<h1>Calorie Intake</h1>

<table>
  <thead>
    <tr>
      <th>Calories</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choloric_intake.each do |choloric_intake| %>
      <tr>
        <td><%= choloric_intake.calories %></td>
        <td><%= choloric_intake.date %></td>
        <td><%= link_to 'Show', choloric_intake %></td>
        <td><%= link_to 'Edit', edit_choloric_intake_path(choloric_intake) %></td>
        <td><%= link_to 'Destroy', choloric_intake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="actions">
<%= link_to 'Enter Calories', new_choloric_intake_path %>
</div>
<div class="actions">
<%= link_to "Dashboard", root_path %>
</div>

app/views/choloric_intakes/new.html.erb
<h1>You ate another sandwhich? Uhhh...  Enter your calories.</h1>

<%= render 'form' %>

<div class="actions">
<%= link_to 'Back', choloric_intakes_path %>
</div>

app/views/choloric_intakes/post.html.erb
<h1>You ate another sandwhich? Uhhh...  Enter your calories.</h1>



<%= link_to 'Back', choloric_intakes_index_path %>

app/views/choloric_intakes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calories:</strong>
  <%= @choloric_intake.calories %>
</p>

<p>
  <strong>Date:</strong>
  <%= @choloric_intake.date %>
</p>
<div class="actions">
  <%= link_to 'Edit', edit_choloric_intake_path(@choloric_intake) %> |
  <%= link_to 'Back', choloric_intake_path %>
</div>

<div class="actions">
  <%= link_to 'Homepage', root_path %>
</div>